### ISSUE TITLE
 Already disconnected error and no buffer details

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#120]
Already disconnected
Sorry, the connection to the server has been destroyed. Please reload. Details of buffer:

happened on URL https://videomail.io/

at origin

(undefined)

error code

code=undefined, type=undefined, name=undefined

Client

{
 "browser": {
  "name": "Chrome",
  "version": "58.0.3029.110",
  "major": "58"
 },
 "device": {},
 "os": {
  "name": "Windows",
  "version": "10"
 },
 "engine": {
  "version": "537.36",
  "name": "WebKit"
 },
 "userAgent": null
}

has cookies

(undefined)

Log lines

[debug] #videomail [18:05:43] > Client: interactive(), previousState = 4, !building = true, !isBuilt() = true
[debug] #videomail [18:05:43] > Container: build()
[debug] #videomail [18:05:43] > Container: initEvents()
[debug] #videomail [18:05:43] > Container: buildForm()
[debug] #videomail [18:05:43] > Container: buildChildren()
[debug] #videomail [18:05:43] > Visuals: buildChildren()
[debug] #videomail [18:05:43] > Notifier: build()
[debug] #videomail [18:05:43] > Notifier: initEvents()
[debug] #videomail [18:05:43] > RecorderInsides: build()
[debug] #videomail [18:05:43] > Replay: build()
[debug] #videomail [18:05:43] > Replay: buildElement()
[debug] #videomail [18:05:43] > Replay: hide()
[debug] #videomail [18:05:43] > Replay: built.
[debug] #videomail [18:05:43] > Visuals: built.
[debug] #videomail [18:05:43] > Container: built.
[debug] #videomail [18:05:43] > Container emits: BUILT
[debug] #videomail [18:05:43] > Recorder: initialising web socket to wss://videomail.io
[debug] #videomail [18:05:43] > Recorder emits: CONNECTING
[debug] #videomail [18:05:43] > Notifier: notify()
[debug] #videomail [18:05:43] > Notifier emits: NOTIFYING
[debug] #videomail [18:05:43] > Replay: hide()
[debug] #videomail [18:05:43] > Recorder: clearRetryTimeout()
[debug] #videomail [18:05:43] > Container emits: FORM_READY [ { paused: false } ]
[debug] #videomail [18:05:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *resume* event emitted
[debug] #videomail [18:05:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *uncork* event emitted
[debug] #videomail [18:05:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *connect* event emitted
[debug] #videomail [18:05:43] > Recorder emits: CONNECTED
[debug] #videomail [18:05:43] > Going to ask for webcam permissons now ...
[debug] #videomail [18:05:44] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *data* event emitted
[debug] #videomail [18:05:44] > Server commanded: ready 
[debug] #videomail [02:21:49] > VideomailError: create()

Stack

Videomail Error: Already disconnected
    at Function.VideomailError.create (https://videomail.io/js/main-9f5af536ba.min.js:28:8771)
    at writeStream (https://videomail.io/js/main-9f5af536ba.min.js:29:24553)
    at https://videomail.io/js/main-9f5af536ba.min.js:29:25077

Who created the VideomailError (caller)?

(undefined)

**Comment by binarykitchen** [comment]
fixed
