### ISSUE TITLE
Webcam has no audio

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#125]
Improve this error message

Webcam has no audio
InvalidStateError: Failed to execute 'createMediaStreamSource' on 'BaseAudioContext': MediaStream has no audio trackDetails: {}

happened on URL https://videomail.io/

at origin

(undefined)

error code

code=undefined, type=undefined, name=undefined

Client

{
 "browser": {
  "name": "Chrome",
  "version": "59.0.3071.115",
  "major": "59"
 },
 "device": {},
 "os": {
  "name": "Windows",
  "version": "7"
 },
 "engine": {
  "name": "WebKit",
  "version": "537.36"
 },
 "userAgent": null
}

has cookies

(undefined)

Log lines

[debug] #videomail [17:48:41] > Client: interactive(), previousState = 4, !building = true, !isBuilt() = true
[debug] #videomail [17:48:41] > Container: build()
[debug] #videomail [17:48:41] > Container: initEvents()
[debug] #videomail [17:48:41] > Container: buildForm()
[debug] #videomail [17:48:41] > Container: buildChildren()
[debug] #videomail [17:48:41] > Visuals: buildChildren()
[debug] #videomail [17:48:41] > Notifier: build()
[debug] #videomail [17:48:41] > Notifier: initEvents()
[debug] #videomail [17:48:41] > RecorderInsides: build()
[debug] #videomail [17:48:41] > Replay: build()
[debug] #videomail [17:48:41] > Replay: buildElement()
[debug] #videomail [17:48:41] > Replay: hide()
[debug] #videomail [17:48:41] > Replay: built.
[debug] #videomail [17:48:41] > Visuals: built.
[debug] #videomail [17:48:41] > Container: built.
[debug] #videomail [17:48:41] > Container emits: BUILT
[debug] #videomail [17:48:41] > Recorder: initialising web socket to wss://videomail.io
[debug] #videomail [17:48:41] > Recorder emits: CONNECTING
[debug] #videomail [17:48:41] > Notifier: notify()
[debug] #videomail [17:48:41] > Notifier emits: NOTIFYING
[debug] #videomail [17:48:41] > Replay: hide()
[debug] #videomail [17:48:41] > Recorder: clearRetryTimeout()
[debug] #videomail [17:48:41] > Container emits: FORM_READY [ { paused: false } ]
[debug] #videomail [17:48:42] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *resume* event emitted
[debug] #videomail [17:48:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *uncork* event emitted
[debug] #videomail [17:48:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *connect* event emitted
[debug] #videomail [17:48:43] > Recorder emits: CONNECTED
[debug] #videomail [17:48:43] > Going to ask for webcam permissons now ...
[debug] #videomail [17:48:43] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *data* event emitted
[debug] #videomail [17:48:43] > Server commanded: ready 
[debug] #videomail [17:49:17] > VideomailError: create()

Stack

Videomail Error: Webcam has no audio
    at Function.VideomailError.create (https://videomail.io/js/main-ee6c3901df.min.js:1:892496)
    at exports.default.init (https://videomail.io/js/main-ee6c3901df.min.js:1:872691)
    at fireCallbacks (https://videomail.io/js/main-ee6c3901df.min.js:1:976530)
    at HTMLVideoElement.onLoadedMetaData (https://videomail.io/js/main-ee6c3901df.min.js:1:977768)

**Comment by binarykitchen** [comment]
fixed
