### ISSUE TITLE
Prettify InvalidStateError

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#149]
InvalidStateError
(no explanation)

happened on URL https://videomail.io/

at origin

(undefined)

error code

code=undefined, type=undefined, name=InvalidStateError

Client

{
 "browser": {
  "name": "Chrome",
  "version": "38.0.2125.122",
  "major": "38"
 },
 "device": {},
 "os": {
  "name": "Linux"
 },
 "engine": {
  "name": "WebKit",
  "version": "537.31"
 },
 "userAgent": null
}

has cookies

(undefined)

Log lines

[debug] #videomail [01:00:19] > Client: interactive(), previousState = 4, !building = true, !isBuilt() = true
[debug] #videomail [01:00:19] > Container: initEvents()
[debug] #videomail [01:00:19] > Container: buildForm()
[debug] #videomail [01:00:20] > Container: buildChildren()
[debug] #videomail [01:00:20] > Buttons: initEvents()
[debug] #videomail [01:00:20] > Visuals: initEvents()
[debug] #videomail [01:00:20] > Visuals: buildChildren()
[debug] #videomail [01:00:20] > Notifier: build()
[debug] #videomail [01:00:20] > Notifier: initEvents()
[debug] #videomail [01:00:20] > RecorderInsides: build()
[debug] #videomail [01:00:20] > RecorderInsides: initEvents()
[debug] #videomail [01:00:20] > Replay: build()
[debug] #videomail [01:00:20] > Replay: buildElement()
[debug] #videomail [01:00:20] > Replay: built.
[debug] #videomail [01:00:20] > Visuals: built.
[debug] #videomail [01:00:20] > Container: built.
[debug] #videomail [01:00:20] > Container emits: BUILT
[debug] #videomail [01:00:20] > Recorder: initEvents()
[debug] #videomail [01:00:20] > Recorder: initialising web socket to wss://videomail.io
[debug] #videomail [01:00:20] > Recorder emits: CONNECTING
[debug] #videomail [01:00:20] > Notifier: notify()
[debug] #videomail [01:00:20] > Notifier emits: NOTIFYING
[debug] #videomail [01:00:20] > Recorder: clearRetryTimeout()
[debug] #videomail [01:00:20] > Container emits: FORM_READY [ { paused: false } ]
[debug] #videomail [01:00:20] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *resume* event emitted
[debug] #videomail [01:00:21] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *uncork* event emitted
[debug] #videomail [01:00:21] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *connect* event emitted
[debug] #videomail [01:00:21] > Recorder emits: CONNECTED
[debug] #videomail [01:00:21] > Going to ask for webcam permissons now ...
[debug] #videomail [01:00:22] > °º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸ Stream *data* event emitted
[debug] #videomail [01:00:44] > VideomailError: create() { constraintName: '', message: '', name: 'InvalidStateError' } undefined

Stack

Videomail Error: InvalidStateError
    at Function.VideomailError.create (https://videomail.io/js/main-d20203ff4c.min.js:1:911747)
    at userMediaErrorCallback (https://videomail.io/js/main-d20203ff4c.min.js:1:975056)

**Comment by binarykitchen** [comment]
added a try catch block - see if it gets caught

**Comment by binarykitchen** [comment]
doesnt happen anymore
