### ISSUE TITLE
TypeError: Object doesn't support property or method 'on'

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#33]
Happens on IE 10

```
TypeError: Object doesn't support property or method 'on'
at on (https://videomail.io/js/main-205ea0e868.js:41602:9)
at initForm (https://videomail.io/js/main-205ea0e868.js:48862:9)
at init (https://videomail.io/js/main-205ea0e868.js:48883:13)
at exports (https://videomail.io/js/main-205ea0e868.js:48886:5)
at invoke (https://videomail.io/js/main-205ea0e868.js:7580:7)
at instantiate (https://videomail.io/js/main-205ea0e868.js:7588:7)
at Anonymous function (https://videomail.io/js/main-205ea0e868.js:11894:7)
at link (https://videomail.io/js/main-205ea0e868.js:3341:9)
at invokeLinkFn (https://videomail.io/js/main-205ea0e868.js:11651:9)
at nodeLinkFn (https://videomail.io/js/main-205ea0e868.js:11161:11)
```

**Comment by binarykitchen** [comment]
Caused by https://github.com/teawithfruit/node-singleton-event/issues/5 ...

probably I should build in some IE10 recognition?

**Comment by binarykitchen** [comment]
For that, use https://github.com/binarykitchen/despot

**Comment by binarykitchen** [comment]
done
