### ISSUE TITLE
Error: Failed to access media for audio

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#80]
```
onerror: "Uncaught Videomail Error: Failed to access media for audio."

occured at https://videomail.io/

caused by useragent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 OPR/36.0.2130.65

https://videomail.io/js/main-a5d65e77a7.min.js:21:16828

[object Object]
[object Object]
[object Object]
[object Object]

Log lines

[error] #videomail > Videomail Error: Cannot access webcam!
    at Function.VideomailError.create (https://videomail.io/js/main-a5d65e77a7.min.js:21:30295)
    at getNoAccessIssue (https://videomail.io/js/main-a5d65e77a7.min.js:21:22496)
    at https://videomail.io/js/main-a5d65e77a7.min.js:23:8127
```

**Comment by binarykitchen** [comment]
can't do much here
